apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-assistant
  labels:
    app: product-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-assistant
  template:
    metadata:
      labels:
        app: product-assistant
    spec:
      containers:
      - name: product-assistant
        image: 459497895986.dkr.ecr.us-east-2.amazonaws.com/product-assistant:latest
        ports:
        - containerPort: 8000
